<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useLocationsStore } from '@/stores/locations'
import { useCaptionsStore } from '@/stores/captions'
import { onBeforeRouteLeave } from 'vue-router'
import ThemeToggle from '@/components/ThemeToggle.vue'
import ConnectionBar from '@/components/ConnectionBar.vue'
const route = useRoute()
const locationStore = useLocationsStore()
const captionStore = useCaptionsStore()
const loc = String(route.params.location)
const location = computed(() => {
  return locationStore.getLocation(loc)
})
const captions = computed(() => {
  return captionStore.getCaptions(loc)
})
const latest = computed(() => {
  return captionStore.getLatest(loc)
})
onMounted(async () => {
  captionStore.fetchCaptions(loc)
  captionStore.joinRoom(loc)
})
onBeforeRouteLeave((to, from) => {
  captionStore.leaveRoom(loc)
})
</script>

<template>
  <div>
    <nav class="links">
      <router-link class="link-btn" :to="{ name: 'index' }">
        <div class="link">
          <div>
            <div class="link-icon">⬅</div>
            back
          </div>
        </div>
      </router-link>
      <ThemeToggle></ThemeToggle>
    </nav>
    <main class="page">
      <div v-if="location">
        <h1>{{ location.name }} Captions</h1>
        <div v-if="!captions.length && !latest.text" class="captionbox">
          <p>There are currently no captions available.</p>
          <p>Please contact the Duty Technician on 1075 if you think there is a problem.</p>
        </div>
        <div v-else class="captionbox" ref="captionBox">
          <span v-if="latest">{{ latest.text }}</span>
          <span v-for="caption in captions" v-bind:key="caption.timestamp">{{ caption.text }}</span>
        </div>
      </div>
      <div v-else></div>
      <div class="disclaimer">
        <p>Please note, captions are being generated by an open source neural net running on-site. Results may vary.</p>
      </div>
    </main>
    <ConnectionBar></ConnectionBar>
  </div>
</template>
