<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import QrcodeVue from 'qrcode.vue'
import { useLocationsStore } from '@/stores/locations'
import { useCaptionsStore } from '@/stores/captions'
import { onBeforeRouteLeave } from 'vue-router'
import ConnectionBar from '@/components/ConnectionBar.vue'
const route = useRoute()
const locationStore = useLocationsStore()
const captionStore = useCaptionsStore()
const loc = String(route.params.location)
const qrMargin = 5
const qrSize = 200
const captionBox = ref<null | { scrollTop: null; scrollHeight: null }>(null)
const location = computed(() => {
  return locationStore.getLocation(loc)
})
const captions = computed(() => {
  return captionStore.getCaptions(loc)
})
const latest = computed(() => {
  return captionStore.getLatest(loc)
})
watch([latest, captions], () => {
  if (captionBox.value) {
    captionBox.value.scrollTop = captionBox.value.scrollHeight
  }
})
const stageQR = computed(() => {
  if ('location' in locationStore.getLocation(loc)) {
    return 'https://captions.emf.camp/live/' + locationStore.getLocation(loc).location
  }
  return 'https://captions.emf.camp'
})
onMounted(async () => {
  captionStore.fetchCaptions(loc)
  captionStore.joinRoom(loc)
})
onBeforeRouteLeave((to, from) => {
  captionStore.leaveRoom(loc)
})
</script>

<template>
  <main class="page">
    <div v-if="location">
      <div v-if="!captions.length && !latest.text" class="captionboxscreen">
        <p>There are currently no captions available.</p>
      </div>
      <div v-else class="captionboxscreen" ref="captionBox">
        <span v-for="caption in captions" v-bind:key="caption.timestamp">{{ caption.text }}</span>
        <span v-if="latest" class="latest">{{ latest.text }}</span>
      </div>
      <div class="qrbox">
        <div>
          <qrcode-vue
            :value="stageQR"
            level="M"
            :size="qrSize"
            :margin="qrMargin"
            render-as="svg"
          />
        </div>
        <div class="qrtext">
          Scan the QR code to view captions on your personal device or visit
          <u>captions.emf.camp</u>
        </div>
      </div>
      <div class="disclaimer">
        <p>
          Please note, captions are being generated by an open source neural net running on-site.
          Results may vary.
        </p>
      </div>
    </div>
    <div v-else></div>
    <ConnectionBar></ConnectionBar>
  </main>
</template>
